import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";
import { AdminMenus } from "@/data/Sidebar";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const giloryBold = localFont({
  src: "./fonts/Gilroy-Bold.ttf",
  style: "normal",
  variable: "--font-giloryBold",
});

export const metadata: Metadata = {
  title: "QueueUp",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${giloryBold.variable} antialiased`}
      >
        <div className="flex relative">
          <div className="fixed inset-0 -z-10">
            <div className="absolute inset-0 bg-[url('/images/background.png')] bg-cover bg-center opacity-60"></div>
            <div className="absolute inset-0 bg-[#6A7589] opacity-80"></div>
          </div>
          <div className="hidden lg:block">
            <Sidebar menus={AdminMenus} />
          </div>
          <div className="lg:ml-[200px] xl:ml-[240px] 2xl:ml-[300px] w-full px-4 py-4">
            <Header />
            <main className="mt-[3rem] sm:mt-[5.4rem]">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
